name: projector-development

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: projector-postgres

volumes:
  postgres-volume:

networks:
  default:
    driver: bridge
