name: projector-development

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    container_name: projector-postgres

volumes:
  postgres-volume:

networks:
  default:
    driver: bridge
