name: projector

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    container_name: projector-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres-network

  api:
    image: ghcr.io/thisislinuxmasterrace/projector-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    container_name: projector-api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - shared-network
      - postgres-network

  frontend:
    image: ghcr.io/thisislinuxmasterrace/projector-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - api
    container_name: projector-frontend
    networks:
      - shared-network

volumes:
  postgres-volume:

networks:
  shared-network:
    external: true
  postgres-network:
    driver: bridge