name: projector

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: projector-postgres

  api:
    image: ghcr.io/thisislinuxmasterrace/projector-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    container_name: projector-api

  frontend:
    image: ghcr.io/thisislinuxmasterrace/projector-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - frontend-build:/app/build
    depends_on:
      - api
    env_file:
      - .env
    container_name: projector-frontend

  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ${CERTS_PATH}:/etc/letsencrypt
      - ${CERTS_DATA_PATH}:/var/lib/letsencrypt
      - frontend-build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/templates/default.conf.conf
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    depends_on:
      - frontend
      - api
    env_file:
      - .env
    container_name: projector-nginx

volumes:
  postgres-volume:
  frontend-build:

networks:
  default:
    driver: bridge
