name: projector

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  api:
    image: ghcr.io/thisislinuxmasterrace/api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
#  nginx:
#    restart: unless-stopped
#    image: nginx:1.19-alpine
#    volumes:
#      - ./nginx.conf:/etc/nginx/templates/default.conf.template
#   env_file:
#      - .env
#    ports:
#      - "${NGINX_PORT}:${NGINX_PORT}"
#    depends_on:
#      - api

volumes:
  postgres-volume:
