name: projector

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-network
    env_file:
      - .env

  api:
    image: ghcr.io/thisislinuxmasterrace/api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - postgres-network
    env_file:
      - .env
    
  frontend:
    image: ghcr.io/thisislinuxmasterrace/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - frontend-build:/usr/share/nginx/html
    depends_on:
      - api
    env_file:
      - .env

  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - frontend-build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - frontend
      - api
    env_file:
      - .env

volumes:
  postgres-volume:
  frontend-build:

networks:
  postgres-network:
    driver: bridge
