name: projector

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: projector-postgres
    networks:
      - shared-network

  api:
    image: ghcr.io/thisislinuxmasterrace/projector-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    container_name: projector-api
    networks:
      - shared-network

  frontend:
    image: ghcr.io/thisislinuxmasterrace/projector-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - frontend-build:/app/build
    depends_on:
      - api
    env_file:
      - .env
    container_name: projector-frontend
    networks:
      - shared-network

  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ${CERTS_PATH}:/etc/letsencrypt
      - ${CERTS_DATA_PATH}:/var/lib/letsencrypt
      - frontend-build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/templates/default.conf.conf
    depends_on:
      - frontend
      - api
    env_file:
      - .env
    container_name: projector-nginx
    networks:
      - shared-network

volumes:
  postgres-volume:
  frontend-build:

networks:
  shared-network:
    external: true
